name: bindcompare
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - customtkinter
  - matplotlib-base
  - biopython
  - intervaltree
  # - samtools
  # - bedtools
  # - r-optparse
  # - r-gprofiler2
  # - meme